# **MÓDULO 14 - Exercício**
# Pré Processamento dos Dados - A primeira etapa Pré Modelagem

Para nossa atividade usaremos uma base de churn também, porém essa base não diz respeito a serviços bancários e sim serviços de internet, telefone e tv - Telecomunicação.

Vamos realizar aqui as etapas de limpeza e tratamento de dados vistos durante a aula, porém aplicados a essa base nova.

In [ ]:
import seaborn as sns
import matplotlib.pyplot as plt
import pandas as pd

In [2]:
#Lembrem-se sempre de alterar a importação dos dados de acordo com o diretório de vocês.
df = pd.read_csv(r"C:\Users\DELL\Documents\ebac\portifolios\CHURN_TELECON_MOD08_TAREFA.csv", delimiter=';')

df.head(10)

,Unnamed: 0,customerID,Genero,Idoso,Casado,Dependents,Tempo_como_Cliente,PhoneService,Servico_Internet,Servico_Seguranca,Suporte_Tecnico,StreamingTV,Tipo_Contrato,PaymentMethod,Pagamento_Mensal,Total_Pago,Churn
0,0,7590-VHVEG,Female,0,Yes,No,1,No,DSL,No,No,No,Month-to-month,Electronic check,29.85,29.85,No
1,1,5575-GNVDE,Male,0,No,No,34,Yes,DSL,Yes,No,No,One year,Mailed check,56.95,1889.50,No
2,2,3668-QPYBK,Male,0,No,No,2,Yes,DSL,Yes,No,No,Month-to-month,Mailed check,53.85,108.15,Yes
3,3,7795-CFOCW,Male,0,No,No,45,No,DSL,Yes,Yes,No,One year,Bank transfer (automatic),NaN,1840.75,No
4,4,9237-HQITU,NaN,0,No,No,2,Yes,Fiber optic,No,No,No,Month-to-month,Electronic check,NaN,151.65,Yes
5,5,9305-CDSKC,NaN,0,No,No,8,Yes,Fiber optic,No,No,Yes,Month-to-month,Electronic check,NaN,820.50,NaN
6,6,1452-KIOVK,NaN,0,No,Yes,22,Yes,Fiber optic,No,No,Yes,Month-to-month,Credit card (automatic),NaN,1949.40,NaN
7,7,6713-OKOMC,NaN,0,No,No,10,No,DSL,Yes,No,No,Month-to-month,Mailed check,NaN,301.90,NaN
8,8,7892-POOKP,NaN,0,Yes,No,28,Yes,Fiber optic,No,Yes,Yes,Month-to-month,Electronic check,NaN,3046.05,NaN
9,9,6388-TABGU,NaN,0,No,Yes,62,Yes,dsl,Yes,No,No,One year,Bank transfer (automatic),NaN,3487.95,NaN

Legenda dos dados:

*   **CustomerID** : Esse é o ID único de cada cliente nosso da rede de produtos de telecomunicação.

*   **Genero** : O genero dos nossos clientes.

*   **Idoso** : Se nosso cliente tem acima de 60 anos ou não. (Sim = 1 | Não = 0)

*   **Casado** : Se nosso cliente é casado ou não.

*   **Dependents** : Se cliente tem dependentes.

*   **Tempo_como_Cliente** : Tempo em meses que nosso cliente está com a nossa empresa.

*   **PhoneService** : Se ele contratou serviço telefônico com a nossa empresa.

*   **Servico_Internet** : Qual o tipo de serviço de internet contratado.

*   **Servico_Seguranca** : Se ele contratou serviço de segurança com a nossa empresa.

*   **Suporte_Tecnico** : Se já acionou o suporte técnico.

*   **StreamingTV** : Se ele contratou serviço de streaming para TV.

*   **Tipo_Contrato** : Qual o tipo de contrato dos nossos clientes, se era mensal, anual etc.

*   **Tipo_Contrato** : Qual o tipo de contrato dos nossos clientes, se era mensal, anual etc.

*   **PaymentMethod** : Forma de Pagamento.

*   **Pagamento_Mensal** : Quanto o cliente pagava mensalmente.

*   **Total_Pago** : Total já pago pelo cliente para nossa companhia.

*   **Churn** : Nossa coluna mais importante, se nosso cliente nos abandonou ou não.

# 1 - Carregue a base, verifique se os tipos de dados estão de acordo com cada coluna e caso não estejam realize a transformação dos tipos de dados.

In [1]:
import pandas as pd

# Atualizando o caminho correto da base de dados no seu computador
file_path = r'C:\Users\DELL\Documents\ebac\portifolios\CHURN_TELECON_MOD08_TAREFA.csv'

# Carregar o dataset
df = pd.read_csv(file_path, delimiter=';')

# Exibir os primeiros 10 registros
df.head(10)

,Unnamed: 0,customerID,Genero,Idoso,Casado,Dependents,Tempo_como_Cliente,PhoneService,Servico_Internet,Servico_Seguranca,Suporte_Tecnico,StreamingTV,Tipo_Contrato,PaymentMethod,Pagamento_Mensal,Total_Pago,Churn
0,0,7590-VHVEG,Female,0,Yes,No,1,No,DSL,No,No,No,Month-to-month,Electronic check,29.85,29.85,No
1,1,5575-GNVDE,Male,0,No,No,34,Yes,DSL,Yes,No,No,One year,Mailed check,56.95,1889.50,No
2,2,3668-QPYBK,Male,0,No,No,2,Yes,DSL,Yes,No,No,Month-to-month,Mailed check,53.85,108.15,Yes
3,3,7795-CFOCW,Male,0,No,No,45,No,DSL,Yes,Yes,No,One year,Bank transfer (automatic),NaN,1840.75,No
4,4,9237-HQITU,NaN,0,No,No,2,Yes,Fiber optic,No,No,No,Month-to-month,Electronic check,NaN,151.65,Yes
5,5,9305-CDSKC,NaN,0,No,No,8,Yes,Fiber optic,No,No,Yes,Month-to-month,Electronic check,NaN,820.50,NaN
6,6,1452-KIOVK,NaN,0,No,Yes,22,Yes,Fiber optic,No,No,Yes,Month-to-month,Credit card (automatic),NaN,1949.40,NaN
7,7,6713-OKOMC,NaN,0,No,No,10,No,DSL,Yes,No,No,Month-to-month,Mailed check,NaN,301.90,NaN
8,8,7892-POOKP,NaN,0,Yes,No,28,Yes,Fiber optic,No,Yes,Yes,Month-to-month,Electronic check,NaN,3046.05,NaN
9,9,6388-TABGU,NaN,0,No,Yes,62,Yes,dsl,Yes,No,No,One year,Bank transfer (automatic),NaN,3487.95,NaN

# 2 - Esse exercício faremos por etapas:
A) Verifique se temos colunas com dados faltantes e traga a % dos dados faltantes por coluna.

In [3]:
# Verificar a porcentagem de dados faltantes por coluna
missing_data_percentage = df.isnull().mean() * 100
print(missing_data_percentage)

Unnamed: 0             0.0
customerID             0.0
Genero                60.0
Idoso                  0.0
Casado                 0.0
Dependents             0.0
Tempo_como_Cliente     0.0
PhoneService           0.0
Servico_Internet       0.0
Servico_Seguranca      0.0
Suporte_Tecnico        0.0
StreamingTV            0.0
Tipo_Contrato          0.0
PaymentMethod          0.0
Pagamento_Mensal      70.0
Total_Pago             0.0
Churn                 50.0
dtype: float64

B) Exclua nessa etapa as linhas das colunas com dados faltantes que você analisar que esse método é o ideal. Justifique o motivo de estar excluindo essas linhas.

In [4]:
# Excluir as linhas onde os dados são críticos (por exemplo, gênero ou churn)
df_cleaned = df.dropna(subset=['Genero', 'Churn'])

# Verificar se as linhas foram removidas
df_cleaned.info()

<class 'pandas.core.frame.DataFrame'>
Index: 4 entries, 0 to 3
Data columns (total 17 columns):
 #   Column              Non-Null Count  Dtype
---  ------              --------------  -----
 0   Unnamed: 0          4 non-null      int64
 1   customerID          4 non-null      object
 2   Genero              4 non-null      object
 3   Idoso               4 non-null      int64
 4   Casado              4 non-null      object
 5   Dependents          4 non-null      object
 6   Tempo_como_Cliente  4 non-null      int64
 7   PhoneService        4 non-null      object
 8   Servico_Internet    4 non-null      object
 9   Servico_Seguranca   4 non-null      object
 10  Suporte_Tecnico     4 non-null      object
 11  StreamingTV         4 non-null      object
 12  Tipo_Contrato       4 non-null      object
 13  PaymentMethod       4 non-null      object
 14  Pagamento_Mensal    3 non-null      float64
 15  Total_Pago          4 non-null      float64
 16  Churn               4 non-null      object
dtypes: float64(2), int64(3), object(12)
memory usage: 576.0+ bytes

C) Nessa etapa substitua pela média, mediana ou moda as linhas das colunas com valores faltantes que você analisou e entendeu que esse era o melhor método. Não se esqueça de justificar sua escolha.

**Dica variáveis numéricas:** Não se esqueça de verificar a distrbuição dos dados, média e mediana.

**Dica variáveis categóricas:** Caso precise substituir uma variável categórica utilize um gráfico de barras para verificar a que mais aparece e utilizar ela na substituição.
Ou você pode optar por excluir a coluna, mas justifique sua escolha.

Caso opte por substituir você pode utilizar a função fillna:
df['SUACOLUNA'].fillna("VALOR QUE SUBSTITUIRA O NULO", inplace=True)
Ela funcionará como a replace.

In [19]:
# Certifique-se de que df_cleaned é uma cópia do DataFrame original
df_cleaned = df.copy() 

# Verificar as colunas do DataFrame
print(df_cleaned.columns)

# Renomear colunas para remover espaços em branco de forma segura
df_cleaned = df_cleaned.rename(columns=lambda x: x.strip())

# Tratar valores ausentes
if 'Pagamento_Mensal' in df_cleaned.columns:
    df_cleaned['Pagamento_Mensal'] = df_cleaned['Pagamento_Mensal'].fillna(df_cleaned['Pagamento_Mensal'].mean())
else:
    print("A coluna 'Pagamento_Mensal' não está no DataFrame.")

if 'Total_Pago' in df_cleaned.columns:
    df_cleaned['Total_Pago'] = df_cleaned['Total_Pago'].fillna(df_cleaned['Total_Pago'].median())
else:
    print("A coluna 'Total_Pago' não está no DataFrame.")

if 'PaymentMethod' in df_cleaned.columns:
    df_cleaned['PaymentMethod'] = df_cleaned['PaymentMethod'].fillna(df_cleaned['PaymentMethod'].mode()[0])
else:
    print("A coluna 'PaymentMethod' não está no DataFrame.")

# Exibir o DataFrame após tratamento de valores ausentes
print(df_cleaned)

Index(['Unnamed: 0', 'customerID', 'Genero', 'Idoso', 'Casado', 'Dependents',
       'Tempo_como_Cliente', 'PhoneService', 'Servico_Internet',
       'Servico_Seguranca', 'Suporte_Tecnico', 'StreamingTV', 'Tipo_Contrato',
       'PaymentMethod', 'Pagamento_Mensal', 'Total_Pago', 'Churn'],
      dtype='object')
   Unnamed: 0  customerID  Genero  Idoso Casado Dependents  \
0           0  7590-VHVEG  Female      0    Yes         No
1           1  5575-GNVDE    Male      0     No         No
2           2  3668-QPYBK    Male      0     No         No
3           3  7795-CFOCW    Male      0     No         No
4           4  9237-HQITU     NaN      0     No         No
5           5  9305-CDSKC     NaN      0     No         No
6           6  1452-KIOVK     NaN      0     No        Yes
7           7  6713-OKOMC     NaN      0     No         No
8           8  7892-POOKP     NaN      0    Yes         No
9           9  6388-TABGU     NaN      0     No        Yes

   Tempo_como_Cliente PhoneService Servico_Internet Servico_Seguranca  \
0                   1           No              DSL                No
1                  34          Yes              DSL               Yes
2                   2          Yes              DSL               Yes
3                  45           No              DSL               Yes
4                   2          Yes      Fiber optic                No
5                   8          Yes      Fiber optic                No
6                  22          Yes      Fiber optic                No
7                  10           No              DSL               Yes
8                  28          Yes      Fiber optic                No
9                  62          Yes              dsl               Yes

  Suporte_Tecnico StreamingTV   Tipo_Contrato              PaymentMethod  \
0              No          No  Month-to-month           Electronic check
1              No          No        One year               Mailed check
2              No          No  Month-to-month               Mailed check
3             Yes          No        One year  Bank transfer (automatic)
4              No          No  Month-to-month           Electronic check
5              No         Yes  Month-to-month           Electronic check
6              No         Yes  Month-to-month    Credit card (automatic)
7              No          No  Month-to-month               Mailed check
8             Yes         Yes  Month-to-month           Electronic check
9              No          No        One year  Bank transfer (automatic)

   Pagamento_Mensal  Total_Pago Churn
0         29.850000       29.85    No
1         56.950000     1889.50    No
2         53.850000      108.15   Yes
3         46.883333     1840.75    No
4         46.883333      151.65   Yes
5         46.883333      820.50   NaN
6         46.883333     1949.40   NaN
7         46.883333      301.90   NaN
8         46.883333     3046.05   NaN
9         46.883333     3487.95   NaN

# 3 - Verifique se encontramos valores digitados incorretamente, ou com letras maiusculas ou minusculas, ou até mesmo mesmos valores porém escritos de forma dirente e corrija.

In [18]:
# Corrigir capitalização inconsistente
df_cleaned.loc[:, 'Servico_Internet'] = df_cleaned['Servico_Internet'].str.lower()

# Verificar e substituir valores mal formatados ou duplicados
df_cleaned.loc[:, 'PaymentMethod'] = df_cleaned['PaymentMethod'].replace('Bank transfer (automatic)', 'bank_transfer')

# Exibir o DataFrame após correção de valores
print(df_cleaned)

   Unnamed: 0  customerID  Genero  Idoso Casado Dependents  \
0           0  7590-VHVEG  Female      0    Yes         No
1           1  5575-GNVDE    Male      0     No         No
2           2  3668-QPYBK    Male      0     No         No
3           3  7795-CFOCW    Male      0     No         No
4           4  9237-HQITU     NaN      0     No         No
5           5  9305-CDSKC     NaN      0     No         No
6           6  1452-KIOVK     NaN      0     No        Yes
7           7  6713-OKOMC     NaN      0     No         No
8           8  7892-POOKP     NaN      0    Yes         No
9           9  6388-TABGU     NaN      0     No        Yes

   Tempo_como_Cliente PhoneService Servico_Internet Servico_Seguranca  \
0                   1           No              dsl                No
1                  34          Yes              dsl               Yes
2                   2          Yes              dsl               Yes
3                  45           No              dsl               Yes
4                   2          Yes      fiber optic                No
5                   8          Yes      fiber optic                No
6                  22          Yes      fiber optic                No
7                  10           No              dsl               Yes
8                  28          Yes      fiber optic                No
9                  62          Yes              dsl               Yes

  Suporte_Tecnico StreamingTV   Tipo_Contrato            PaymentMethod  \
0              No          No  Month-to-month         Electronic check
1              No          No        One year             Mailed check
2              No          No  Month-to-month             Mailed check
3             Yes          No        One year            bank_transfer
4              No          No  Month-to-month         Electronic check
5              No         Yes  Month-to-month         Electronic check
6              No         Yes  Month-to-month  Credit card (automatic)
7              No          No  Month-to-month             Mailed check
8             Yes         Yes  Month-to-month         Electronic check
9              No          No        One year            bank_transfer

   Pagamento_Mensal  Total_Pago Churn
0         29.850000       29.85    No
1         56.950000     1889.50    No
2         53.850000      108.15   Yes
3         46.883333     1840.75    No
4         46.883333      151.65   Yes
5         46.883333      820.50   NaN
6         46.883333     1949.40   NaN
7         46.883333      301.90   NaN
8         46.883333     3046.05   NaN
9         46.883333     3487.95   NaN

# [EXTRA] 4 - Caso deseje, para manter um padrão na sua base, renomeie as colunas ou deixand

In [11]:
# Renomear colunas para um formato padronizado (sem espaços e com letras minúsculas)
df_cleaned.columns = df_cleaned.columns.str.lower().str.replace(' ', '_')

# Exibir o DataFrame limpo
df_cleaned.head()

,unnamed:_0,customerid,genero,idoso,casado,dependents,tempo_como_cliente,phoneservice,servico_internet,servico_seguranca,suporte_tecnico,streamingtv,tipo_contrato,paymentmethod,pagamento_mensal,total_pago,churn
0,0,7590-VHVEG,Female,0,Yes,No,1,No,dsl,No,No,No,Month-to-month,Electronic check,29.850000,29.85,No
1,1,5575-GNVDE,Male,0,No,No,34,Yes,dsl,Yes,No,No,One year,Mailed check,56.950000,1889.50,No
2,2,3668-QPYBK,Male,0,No,No,2,Yes,dsl,Yes,No,No,Month-to-month,Mailed check,53.850000,108.15,Yes
3,3,7795-CFOCW,Male,0,No,No,45,No,dsl,Yes,Yes,No,One year,bank_transfer,46.883333,1840.75,No